### ISSUE TITLE
Clicking on "Tutorials" in the header should always take you to the tutorials index page

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#12]
The "Tutorials" link in the header takes you to the page listing all the tutorials except if you're in a tutorial. UX design team says it should behave consistently.

**Comment by ebrent8** [comment]
This one gets me every time.  Hey @jketreno , can you advise me or ODX how to fit this?  I would think this is kinda critical.  I do it every time and it makes the site feel broken.  I'll fix, please tell me what part of the engine to look at.  Thx.

**Steps to reproduce:**  Within any tutorial, the topnav Tutorials link doesn't do anything.  The only way back to the tuts list is the breadcrumb link at top left.

**Comment by BrianOttaway** [comment]
Hello @juliocri ...I see Brent just assigned this one to you a day ago...but, this happens to be a bug that drives me crazy. :) do you have line of sight to knock this out?

**Comment by juliocri** [comment]
Hi @BrianOttaway I remember that once upon the time I did a change for, when you clicked on the 'Tutorial' tab being inside of a tutorial the tab got you to the list page, but the change was not accepted in order to preserve default behave for all tabs (All tabs do nothing when you are within the tab path), I don't remember how I did this change but I can take a look again.

**Comment by jketreno** [comment]
The background on why the original change wasn't taken was to support the interactive usage of being able to switch back and forth between a loaded Tutorial and the Board Explorer, without the pages continually resetting back to their default state. For example, the user loads a tutorial on how to hook up I2C, and they flip to the Board Explorer to read details about Pin 15, they then go back to the Tutorial tab... if it resets to the top index every time, or if the board explorer reset every time you go back to it, it isn't ideal.

That said, an alternative pattern a user would expect is if the pages do reset whenever you click the tab, then control-click a tab should open the tab in a new browser-tab.

@juliocri A way to implement the above might be to put an on-tap handler on the `paper-tab` items in the tab list. When clicked, clear the route to be just the tab name (regardless of the tab.) That should have the same effect as if the user had initially loaded the site on that page.

In addition, you can then check the keyboard to see if the control key is pressed; if so, rather than change the tab and reset the route, `window.open()` a new tab to the new page. We would then have consistency across all of the tabs (they reset the page when you click it) and the ability for the user to keep context and position in whatever content they are in.

Thoughts?

**Comment by juliocri** [comment]
@BrianOttaway , @jketreno  sorry for the late response, but yes I agree, previous solution was inefficient, I just sent a new one to master.. based on tap event from the paper-items.

**Comment by ebrent8** [comment]
Super awesome @juliocri Thank you!!!  Yes it works as expected now on STG.

**Comment by BrianOttaway** [comment]
Sweet. And, yes, it is still retaining the pin selections on the board explorer, if a user was jumping back and forth between tutorial and board exp.

**Comment by ebrent8** [comment]
verified in PROD
