### ISSUE TITLE
Tutorials page: tutorial titles seem smaller than I remember

### ISSUE THREAD

**Issue by dbkinder** [MinnowBoard-org/website#20]
on sxc.jf.intel.com/content.minnow/tutorials, the tutorial titles (in list view) include a class 'title' but on minnowboard.org/tutorials the titles don't have this class applied, so they display with smaller font size.  Was this an intended change or is something wrong?

**Comment by ebrent8** [comment]
Good eye.  Yes this was an intentional change by @jketreno.  The tutorial images are now in list format, but may change to the grid view in the future when we have more. 

Also, having a tutorial selector in the future so users can only see v3 board tuts may change this look and feel as well.

@jketreno can you confirm and close if this is the case?  Thx.

**Comment by jketreno** [comment]
@dbkinder Are you talking about `grid` vs `list` or just a missing class that isn't being applied to the list view data output (very likely something that was just missed when creating the list view)

**Comment by juliocri** [comment]
@ebrent8, @jketreno, @dbkinder This thread seems that have not been updated in about 4 months (conversation), is this still needed?

**Comment by ebrent8** [comment]
Not worth the trouble.  I'm closing.
