### ISSUE TITLE
Redirects for old wiki and search result pages

### ISSUE THREAD

**Issue by ebrent8** [MinnowBoard-org/website#60]
There is a top Google result which points to an old wiki page.  See screenshot.
We need this URL:
https://minnowboard.org/meet-minnowboard-max

To redirect to our homepage: https://minnowboard.org

![unknown](https://cloud.githubusercontent.com/assets/18618930/22165759/4d625d6e-df12-11e6-8511-2cd3fa2cc56f.jpeg)

**Comment by jketreno** [comment]
We can add the redirect; we should perhaps look through the server logs to see inbound links and redirect them all to the main page.

Since I am unable to find the search results you found, what was the search string you looked for to get the above results, and from which browser and OS? In a digital fingerprint free browser, a Google search for "minnowboard" yielded the following:

![image](https://cloud.githubusercontent.com/assets/742584/22166112/46968742-df14-11e6-881e-747514e9648e.png)

 For information on appropriate redirect links and status codes, see the [Moz.com http-status-codes](https://moz.com/learn/seo/http-status-codes) article.

**Comment by ebrent8** [comment]
Yeah having all the old links redirect to the new homepage would be a nice comprehensive way to do it.  @adreanneb sent me the SEO issue, so I don't how she found it.  Hey Adreanne, what were the steps to getting that Google result?  Thx.

**Comment by ebrent8** [comment]
Here's how to recreate that.  Go to Bing.com and search for "minnowboard".

**Comment by adreanneb** [comment]
I used IE!

**Comment by ebrent8** [comment]
Yep cool.  I saw the same results from Safari on my Mac.

**Comment by ebrent8** [comment]
Here's info from @adreanneb, we'll have a quick meeting on this soon to get your direction.


These are the obvious ones:
1.	Turbot: http://wiki.minnowboard.org/MinnowBoard_Turbot to home page https://minnowboard.org/
2.	Where to Buy: http://wiki.minnowboard.org/Where_to_buy to Get a board https://minnowboard.org/get-a-board
3.	About us: http://wiki.minnowboard.org/About_Us to About https://minnowboard.org/about
4.	Community: http://wiki.minnowboard.org/Get_Involved to Community https://minnowboard.org/community
 
Do we redirect or just have a statement on the page that links to the website and remove the content of that page? Something like:
For the most up-to-date information on the MinnowBoard Turbot and the MinnowBoard.org Community, see the new MinnowBoard.org website. Until further notice, MinnowBoard MAX and V1 content is available here on the wiki. 
 
We could even add the statement to the main page of wiki. 



The server running {www.,}minnowboard.org currently does a hostname redirect to the server to wiki.minnowboard.org -- this means if someone tries to go to www.minnowboard.org/Random_URL they are redirected to wiki.minnowboard.org/Random_URL.
Those deep-link URLs have been distributed externally.
We need to look at the server logs and Google analytics to find out which URLs are currently being redirected to from {www.,}minnowboard.org and then come up with a strategy for supporting those URL redirects or not.
Specifically, we need to know:
What URLs have been redirected over the last 6-12 months from {www.,}minnowboard.org to wiki.minnowboard.org
How frequently have those URLs been hit
What is the referrer URL for those hits

gitlab issue 229

**Comment by ebrent8** [comment]
I have a master list of redirects that we'll need from the old wiki and search results.  I think this should coincide with the wiki being shut down but I'll take your advice on it.  I'll sched a meeting.  Peace.

**Comment by noelianunez** [comment]
@ebrent8 did you already had the meeting to discus this? do you need any help from our side? Thanks

**Comment by ebrent8** [comment]
Yes we need ODX and James help with this.  I fwd you an email about it.

**Comment by jketreno** [comment]
@ebrent8 Can you add the list of redirects you want to this issue so I can add it to the server?

**Comment by jketreno** [comment]
You now can edit the list of redirects in the [redirects.json file](https://github.com/MinnowBoard-org/website/edit/master/redirects.json) as documented in [REDIRECT.md](https://github.com/MinnowBoard-org/website/blob/master/REDIRECT.md).

**Comment by jketreno** [comment]
The commit 30835c2 implemented the 301 redirect layer, but it did not close the issue so I re-opened it. 

To complete (and close) the issue:

1. [redirects.json](https://github.com/MinnowBoard-org/website/edit/master/redirects.json) needs to be updated to the complete list of redirect paths
2. The feature needs to be pushed to production
3. A virtual-host entry for wiki.minnowboard.org needs to be added to the server configuration by so that domain name is routed to the minnowboard web application
4. The DNS entry for wiki.minnowboard.org needs to change from pointing to the current IP to point to the minnowboard.org IP.

3 & 4 are changes that need to be done by VTM.

**Comment by ebrent8** [comment]
Redirects PDF attached.  Thank you.

[MinnowBoardRedirects.pdf](https://github.com/MinnowBoard-org/website/files/956789/MinnowBoardRedirects.pdf)

**Comment by jketreno** [comment]
For easier searching, tracking, and indexing, here are the contents of the pdf, with the wiki.minnowboard.org prefix removed (see note at end of this comment)

| key | value |
|:---|:---|
|/MinnowBoard_MAX|/minnowboard-max/|
|/MinnowBoard_Turbot|/|
|/MinnowBoard_Wiki_Home|/|
|/Where_to_buy|/get-a-board/|
|/UEFI|/tutorials/|
|/MinnowBoard_MAX_HW_Setup|/minnowboard-max/|
|/Windows|/tutorials/|
|/Lures|/lures/|
|/meet-minnowboard-max|/legacy-boards/|
|/About_us|/about/|
|/Get_involved|/community/|

The above have been entered into [redirects.json](https://github.com/MinnowBoard-org/website/blob/master/redirects.json).

The final "everything else wiki.*" redirect required an additional code change to check the hostname and issue a 301. That change is on staging.

**NOTE**:

Because the inbound requests are typically **not** listing wiki.minnowboard.org in the URL (see issue #75, which was closed as a duplicate) the redirect cannot be for wiki.minnowboard.org specifically. From issue #75:

> The server running {www.,}minnowboard.org currently does a hostname redirect to the server to wiki.minnowboard.org -- this means if someone tries to go to www.minnowboard.org/Random_URL they are redirected to wiki.minnowboard.org/Random_URL.

>  Those deep-link URLs have been distributed externally.

**Comment by jketreno** [comment]
I have merged the code changes to production and verified that redirects for pages like: [http://www.minnowboard.org/MinnowBoard_MAX_HW_Setup](http://www.minnowboard.org/MinnowBoard_MAX_HW_Setup) are working correctly.

Once steps 3 and 4 of [the above comment](https://github.com/MinnowBoard-org/website/issues/60#issuecomment-297173514) are done by VTM, the redirect for "wiki.minnowboard.org/*" URLs should kick in.

**Comment by ebrent8** [comment]
OK @jketreno - VTM has said that they did 3 and 4 above.  Can you do some tests on your side?

I quickly went to google, typed 'minnowboard', then clicked on the results for 'Minnowboard Max'.
I expected it to redirect to our new '/minnowboard-max' page as shown in the redirect like, but it just went to the homepage.

<img width="706" alt="screen shot 2017-04-27 at 8 18 57 am" src="https://cloud.githubusercontent.com/assets/18618930/25490686/67e9a3ac-2b22-11e7-8484-e251f7359e14.png">

**Comment by jketreno** [comment]
It looks like VTM put in a site wide redirect from https://wiki.minnowboard.org => https://minnowboard.org instead of a virtual host for wiki.minnowboard.org that provides a proxy to the minnowboard web app.

**Comment by ebrent8** [comment]
Hmmm.  Playing telephone between you guys is pretty fun.  I'll CC you on the email to Jim in order to get more specific instructions for them.  Thx.

**Comment by ebrent8** [comment]
Looks good on PROD.  Thank you.
